import lemmaClient from "../../lib/lemma";

export async function createGithubIssue(input: {
  draft_id: string;
  repo: string;
}) {
  const draft = await lemmaClient.records.get("issue_drafts", input.draft_id);
  if (!draft) throw new Error(`Draft ${input.draft_id} not found`);

  const [owner, repo] = input.repo.split("/");
  const token = process.env.GITHUB_TOKEN;

  const body = [
    `## Summary`,
    draft.summary as string,
    ``,
    `## Steps to Reproduce`,
    draft.repro_steps as string,
    ``,
    `## Expected Behavior`,
    draft.expected_behavior as string,
    ``,
    `## Actual Behavior`,
    draft.actual_behavior as string,
    ``,
    `## Severity`,
    `**${(draft.severity as string)?.toUpperCase()}** — Release Risk: **${(draft.release_risk as string)?.toUpperCase()}**`,
    ``,
    `---`,
    `*Generated by Feedback-to-Fix Operator · Cluster ID: ${draft.cluster_id}*`,
  ].join("\n");

  const labels = [
    draft.severity,
    draft.release_risk === "block" ? "release-blocker" : null,
    ...((draft.labels as string[]) || []),
  ].filter(Boolean);

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: draft.title,
      body,
      labels,
    }),
  });

  if (!response.ok) throw new Error(`GitHub API error: ${response.status}`);

  const issue = await response.json();

  await lemmaClient.records.update("issue_drafts", input.draft_id, {
    github_issue_number: issue.number,
    github_issue_url: issue.html_url,
    approval_status: "approved",
  });

  await lemmaClient.records.create("action_log", {
    event_type: "github_issue_created",
    entity_type: "draft",
    entity_id: input.draft_id,
    actor: "system",
    metadata: {
      github_issue_number: issue.number,
      github_issue_url: issue.html_url,
    },
  });

  return {
    success: true,
    issue_number: issue.number,
    issue_url: issue.html_url,
  };
}
